apiVersion: v1
kind: Service
metadata:
  labels:
    run: post-forward
  name: post-forward
  namespace: kubeless
spec:
  type: NodePort
  ports:
  - name: function-port
    port: 8080
    nodePort: 30080
    protocol: TCP
    targetPort: 8080
  selector:
    created-by: kubeless
    function: service

